version: "3"
services:
  vue:
    container_name: dena-hackathon-front
    tty: true
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    working_dir: /home
    volumes:
      - ./app:/home:cached
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
